log:
  name: docker-demo # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: /tmp/iam-authz-server.log,stdout # 多个输出，逗号分开。stdout：标准输出，
  error-output-paths: /tmp/iam-authz-server.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开

base:
  tty: false # 是否启动 tty
  detach: false # 后台运行
  volume: "" # volume 挂载目录
  name: "" # 容器别名
  environment: "" # 设置环境变量
  net: "" # 设置网关
  port: "" # 指定端口映射

limit:
  men: "" # 容器内存限制
  cpu: "" # 容器CPU限制